name: deploy Ecomapp to tomcatserver.GithubActions
on:
  push:
   branches: ["feature"]
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: setup jdk 17
     - uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
         cache: gradle
      - name: build with gradle
        run: grdle -8 package ..file pom.xml
        
      
         
         
